name: docker-ros

on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: RphvK/docker-ros@image-name
        with:
          base-image: rwthika/ros2:humble
          command: ros2 launch spinnaker_camera_driver driver_node.launch.py
